# Generated by Django 5.1.5 on 2025-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
